name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      CLIENT_APP_URL: ${{ secrets.CLIENT_APP_URL }}
      CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
      CLIENT_PASSWORD: ${{ secrets.CLIENT_PASSWORD }}
    container:
      image: mcr.microsoft.com/playwright:v1.34.0-jammy
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Run Playwright tests
        run: yarn test:webchrome
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30
